spring:
  thymeleaf:
    mode: LEGACYHTML5
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    password:


url:
  callback: http://localhost:8080/callback

app:
  client:
    id: d3f10ce3616049e0bddd86f9d3051af0
    secret: b546a60532c14634be9f6b306bbda46b